# Initial training

In [1]:
%load_ext autoreload
%reload_ext autoreload
%autoreload 2

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd



path = 'smoke_detection_iot.csv'

data = pd.read_csv(path).drop(['Unnamed: 0', 'UTC', 'CNT'], axis=1)
Y_df = data['Fire Alarm']
X_df = data.drop('Fire Alarm', axis=1)

Y_test_raw = X_df.values
Y_raw = Y_df.values

X_train_raw, X_test_raw, Y_train_raw, Y_test_raw = train_test_split(Y_test_raw, Y_raw, test_size=0.2, random_state=0)

scaler = StandardScaler()
X_train_raw = scaler.fit_transform(X_train_raw)
X_test_raw = scaler.transform(X_test_raw)

In [2]:
from alarmnetclass import AlarmNet
import torch
from torch import nn

alpha = 1e-2
epochs = 3000
device = 'cuda' if torch.cuda.is_available() else 'cpu'
full_model = AlarmNet(
    num_features=X_train_raw.shape[1],
    activation = nn.ReLU,
    hidden_layers=[64, 32]
    
).to(device)

X_train_raw_device = torch.tensor(X_train_raw).float().to(device)
X_test_raw_device = torch.tensor(X_test_raw).float().to(device)
Y_train_raw_device = torch.tensor(Y_train_raw).float().view(-1, 1).to(device)
Y_test_raw_device = torch.tensor(Y_test_raw).float().view(-1, 1).to(device)
full_model.train(epochs, X_train_raw_device, X_test_raw_device, Y_train_raw_device, Y_test_raw_device, alpha)
full_model.print_results()

Epoch 0 Loss: 0.7198435068130493
Epoch 500 Loss: 0.003261410864070058
Epoch 1000 Loss: 0.003031389322131872
Epoch 1500 Loss: 0.001642040559090674
Epoch 2000 Loss: 0.0010461597703397274
Epoch 2500 Loss: 0.0006817225366830826
Accuracy: 0.9997604981638193
Precision: 0.9998878923766816
Recall: 0.9997758098867839
F1: 0.9998318479905834
Confusion_matrix:
[[3604    1]
 [   2 8919]]
Classification_report:               precision    recall  f1-score   support

         0.0       1.00      1.00      1.00      3605
         1.0       1.00      1.00      1.00      8921

    accuracy                           1.00     12526
   macro avg       1.00      1.00      1.00     12526
weighted avg       1.00      1.00      1.00     12526



# Feature Analysis
- Initially there are 15 features
- 3 are unusable
    - UTC Timestamp
    - CNT
    - Unnamed: 0
- 12 features are usable

In [3]:
import numpy as np



corr = np.abs(data.corr())
ranking = corr['Fire Alarm'].sort_values(ascending=False)[1:]
print(ranking)

Humidity[%]       0.399846
Raw Ethanol       0.340652
Pressure[hPa]     0.249797
TVOC[ppb]         0.214743
Temperature[C]    0.163902
NC0.5             0.128118
PM1.0             0.110552
Raw H2            0.107007
eCO2[ppm]         0.097006
PM2.5             0.084916
NC1.0             0.082828
NC2.5             0.057707
Name: Fire Alarm, dtype: float64


In [4]:
num_drops = 8
remaining_features = ranking.index[:-num_drops]


X_df_dropped = data[remaining_features]
print('Remaining features:', X_df_dropped.columns)
X_train_dropped, X_test_dropped, Y_train_dropped, Y_test_dropped = train_test_split(X_df_dropped.values, Y_raw, test_size=0.2, random_state=0)

X_train_dropped = scaler.fit_transform(X_train_dropped)
X_test_dropped = scaler.transform(X_test_dropped)


Remaining features: Index(['Humidity[%]', 'Raw Ethanol', 'Pressure[hPa]', 'TVOC[ppb]'], dtype='object')


In [5]:
dropped_model = AlarmNet(
    num_features=X_train_dropped.shape[1],
    activation = nn.ReLU,
    hidden_layers=[64, 32]
    
).to(device)

X_train_dropped_device = torch.tensor(X_train_dropped).float().to(device)
X_test_dropped_device = torch.tensor(X_test_dropped).float().to(device)
Y_train_dropped_device = torch.tensor(Y_train_dropped).float().view(-1, 1).to(device)
Y_test_dropped_device = torch.tensor(Y_test_dropped).float().view(-1, 1).to(device)

dropped_model.train(epochs, X_train_dropped_device, X_test_dropped_device, Y_train_dropped_device, Y_test_dropped_device, alpha)
dropped_model.print_results()

AlarmNet.compare_results(dropped_model.get_results(), full_model.get_results())

Epoch 0 Loss: 0.732650637626648
Epoch 500 Loss: 0.05563681572675705
Epoch 1000 Loss: 0.28884029388427734
Epoch 1500 Loss: 0.050261083990335464
Epoch 2000 Loss: 0.054096970707178116
Epoch 2500 Loss: 0.05253012850880623
Accuracy: 0.999041992655277
Precision: 0.9987683350128765
Recall: 0.999887904943392
F1: 0.9993278064082456
Confusion_matrix:
[[3594   11]
 [   1 8920]]
Classification_report:               precision    recall  f1-score   support

         0.0       1.00      1.00      1.00      3605
         1.0       1.00      1.00      1.00      8921

    accuracy                           1.00     12526
   macro avg       1.00      1.00      1.00     12526
weighted avg       1.00      1.00      1.00     12526

Comparing results:
accuracy: -0.07191945021575956 %
precision: -0.1120937983872563 %
recall: 0.01121076233184124 %
f1: -0.050438062376095244 %


## Feature Analysis Results
- We can remove the bottom 8 features and have a model that only loses 0.1% precision, and even less for every other metric
- A 4 feature model is almost perfect
    - These features are:
        - Humidity
        - Raw Ethanol
        - Pressure
        - TVOC

# Error Handling
- The 12 initial features came from 4 sensors
    - Temp/Humidity
    - Pressure
    - Volatile Organic Compounds (CO2, Ethanol, H2, TVOC)
    - Particulate Matter (PM1, PM2.5, NC0.5, NC1, NC2.5)
- 3 of these sensors are redundant, with the exception being the PM sensor
    - This means that the features related to the PM sensor are twice as likely to be missing
- We can simulate a real world scenario by introducing error according to this distribution
- Note that the Particulate Matter sensor is not included in the 4-feature model.
    - To add redundancy to our model, we can add back the most correlated feature from the PM sensor
    - This feature is PM0.5



In [6]:

# Add back the most correlated PM feature, so that all 4 sensors are used
# PM0.5 is the most correlated PM feature, with index 5
remaining_features_2 = list(remaining_features)
remaining_features_2.append(ranking.index[5])
X_5f = data[remaining_features_2]
X_train_5f, X_test_5f, Y_train_5f, Y_test_5f = train_test_split(X_5f.values, Y_raw, test_size=0.2, random_state=0)

scaler = StandardScaler()
X_train_5f = scaler.fit_transform(X_train_5f)
X_test_5f = scaler.transform(X_test_5f)


In [7]:

dropped_model_5 = AlarmNet(
    num_features=X_train_5f.shape[1],  # Update to match the new input dimensions
    activation = nn.ReLU,
    hidden_layers=[64, 32]
    
).to(device)
epochs = 3000
alpha = 1e-2

X_train_5f_device = torch.tensor(X_train_5f).float().to(device)
X_test_5f_device = torch.tensor(X_test_5f).float().to(device)
Y_train_5f_device = torch.tensor(Y_train_raw).float().view(-1, 1).to(device)
Y_test_5f_device = torch.tensor(Y_test_raw).float().view(-1, 1).to(device)

dropped_model_5.train(epochs, X_train_5f_device, X_test_5f_device, Y_train_5f_device, Y_test_5f_device, alpha)

dropped_model_5_results = dropped_model_5.get_results()
dropped_model_5.print_results()

AlarmNet.compare_results(dropped_model_5_results, full_model.get_results())


Epoch 0 Loss: 0.6647908091545105
Epoch 500 Loss: 0.012231706641614437
Epoch 1000 Loss: 0.04820350557565689
Epoch 1500 Loss: 0.008142990991473198
Epoch 2000 Loss: 0.0044751642271876335
Epoch 2500 Loss: 0.002745460020378232
Accuracy: 0.9997604981638193
Precision: 0.9998878923766816
Recall: 0.9997758098867839
F1: 0.9998318479905834
Confusion_matrix:
[[3604    1]
 [   2 8919]]
Classification_report:               precision    recall  f1-score   support

         0.0       1.00      1.00      1.00      3605
         1.0       1.00      1.00      1.00      8921

    accuracy                           1.00     12526
   macro avg       1.00      1.00      1.00     12526
weighted avg       1.00      1.00      1.00     12526

Comparing results:
accuracy: 0.0 %
precision: 0.0 %
recall: 0.0 %
f1: 0.0 %


In [8]:
import random
from sklearn.impute import SimpleImputer

# Introduce sensor errors

VOC_features = [
    'TVOC[ppb]',
    'eCO2[ppm]',
    'Raw H2',
    'Raw Ethanol'
]

PM_features = [
    'PM1.0',
    'PM2.5',
    'NC0.5',
    'NC1.0',
    'NC2.5'
]

th_features = [
    'Temperature[C]',
    'Humidity[%]'
]
pressure_features = [
    'Pressure[hPa]'
]

# For each measurement, each sensor has this chance of introducing an error
error_chance = 0.2

# The PM sensor is twice as likely to fail due to lack of redundancy
chances = [error_chance, error_chance*2, error_chance, error_chance]
sensors = [VOC_features, PM_features, th_features, pressure_features]

error_mask = np.ones(X_5f.shape)

# for i, row in error_mask:
#     errored_features = []
#     for j, sensor in enumerate(sensors):
#         sensor_error = random.random() < chances[j]
#         if sensor_error:
#             errored_features.extend(sensor)
#     errored_features = [feature for feature in errored_features if feature in X_error.columns]
#     if errored_features:
#         for feature in errored_features:
#             error_mask[i][X_error.columns.get_loc(feature)] = np.nan
#         print(i, error_mask[i])

X_error_np = X_5f.values.copy()
for i, datapoint in enumerate(X_5f.values):
    errored_features = []
    for j, sensor in enumerate(sensors):
        sensor_error = random.random() < chances[j]
        if sensor_error:
            errored_features.extend(sensor)
    errored_features = [feature for feature in errored_features if feature in X_5f.columns]
    if errored_features:
        for feature in errored_features:
            X_error_np[i][X_5f.columns.get_loc(feature)] = np.nan
        # print(i, X_error_np[i])

X_train_error, X_test_error, Y_train_error, Y_test_error = train_test_split(X_error_np, Y_raw, test_size=0.2, random_state=0)

## Imputation
- Replace each errored value with the mean of that feature from the training data

In [9]:
imputer = SimpleImputer(strategy='mean')
#imputer.fit(X_5f.values)
imputer.fit(X_train_error)
X_impute_train = imputer.transform(X_train_error)
X_impute_test = imputer.transform(X_test_error)

X_impute_train = scaler.fit_transform(X_impute_train)
X_impute_test = scaler.transform(X_impute_test)

In [20]:
imputed_model = AlarmNet(
    num_features=X_impute_train.shape[1],
    activation = nn.ReLU,
    hidden_layers=[128, 256, 128]
    
).to(device)

X_impute_train_device = torch.tensor(X_impute_train).float().to(device)
X_impute_test_device = torch.tensor(X_impute_test).float().to(device)
Y_train_impute_device = torch.tensor(Y_train_error).float().view(-1, 1).to(device)
Y_test_impute_device = torch.tensor(Y_test_error).float().view(-1, 1).to(device)

imputed_model.train(
    epochs= 16000,
    X_train = X_impute_train_device,
    X_test = X_impute_test_device,
    Y_train = Y_train_impute_device,
    Y_test = Y_test_impute_device,
    alpha= 1e-4,
    loss_fn = nn.BCELoss(),
    optimizer = torch.optim.Adam
)
imputed_model.print_results()
AlarmNet.compare_results(imputed_model.get_results(), dropped_model_5.get_results())

Epoch 0 Loss: 0.7042819261550903
Epoch 500 Loss: 0.17240461707115173
Epoch 1000 Loss: 0.139237180352211
Epoch 1500 Loss: 0.11427774280309677
Epoch 2000 Loss: 0.07477901875972748
Epoch 2500 Loss: 0.0588216632604599
Epoch 3000 Loss: 0.05080319568514824
Epoch 3500 Loss: 0.04612872377038002
Epoch 4000 Loss: 0.04302603378891945
Epoch 4500 Loss: 0.040812019258737564
Epoch 5000 Loss: 0.03922854736447334
Epoch 5500 Loss: 0.038085728883743286
Epoch 6000 Loss: 0.03717287257313728
Epoch 6500 Loss: 0.03650260344147682
Epoch 7000 Loss: 0.03597822040319443
Epoch 7500 Loss: 0.03550107032060623
Epoch 8000 Loss: 0.035160601139068604
Epoch 8500 Loss: 0.03483729064464569
Epoch 9000 Loss: 0.03457602858543396
Epoch 9500 Loss: 0.03438257798552513
Epoch 10000 Loss: 0.03420368954539299
Epoch 10500 Loss: 0.03404993191361427
Epoch 11000 Loss: 0.03393172100186348
Epoch 11500 Loss: 0.03380455821752548
Epoch 12000 Loss: 0.03366152197122574
Epoch 12500 Loss: 0.033522527664899826
Epoch 13000 Loss: 0.0334127023816108

## Error Modes
- Current features:
    - Humidity
    - Raw Ethanol
    - Pressure
    - TVOC
    - NC0.5
- Sensors:
    - Humidity
    - Pressure
    - Raw Ethanol/TVOC
    - NC0.5
- The model should be able to handle missing data in the case where at most 3 sensors have failed, because 4 failed sensors means no data
    - 1 failed sensor = 4c1 = 4
    - 2 failed sensors = 4c2 = 6
    - 3 failed sensors = 4c3 = 4
    - Total = 14
## Ensemble Training
- We can train 14 models that can predict the missing data for each error mode
- In the case of error, we select the model that corresponds to the error mode and use it to predict the missing data
- Then use the main model to predict the target
### Indexing Ensemble
- Columns should be rearranged according to sensors
    - Humidity, Pressure, NC0.5, Ethanol, TVOC, 
- The error mode can be represented as a 4-bit value
    - 0b0000 = No error
    - 0b0001 = Ethanol/TVOC Error
    - 0b0010 = NC0.5 Error
    - 0b0100 = Pressure error
    - 0b1000 = Humidity error
- A 5-bit value can represent which features are missing
    - 0b00000 = No error
    - 0b00011 = Ethanol/TVOC Error
    - 0b00100 = NC0.5 Error
    - 0b01000 = Pressure error
    - 0b10000 = Humidity error
- We can convert from the 5-bit value to the 4-bit value with a simple shift right operation

### Model Table
- Store the models with an array
- The index of the model is the error mode
- Model 15 will always predict 1, because if all sensors have failed the worst should be assumed for safety
- Model 0 will be the standard model trained on a full dataset
- The rest of the arrays will be trained on the data with the corresponding error mode
### New Model Type
- A new model class will be created that will predict the missing values, construct the repaired dataset, call the standard model, and return the result
### Ensemble Class
- This new class will hold the model table and the standard model
- It will be responsible for constructing the model address, calling the correct model, and returning the result



    

